import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  isRTL: boolean;
  formatPrice: (price: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Currency
    'currency.pkr': 'PKR',
    
    // Units
    'unit.page': 'page',
    'unit.pages': 'pages',
    'unit.per': 'per',
    'unit.average': 'average',
    
    // Header/Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.offers': 'Offers',
    'nav.samples': 'Samples',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    
    // Home Page
    'home.hero.title': 'Excel in Your Academic Journey',
    'home.hero.subtitle': 'Empowering Research, Delivering Success',
    'home.hero.viewServices': 'View Services',
    'home.hero.getQuote': 'Get Your Quote',
    
    'home.services.title': 'Our Academic Services',
    'home.services.subtitle': 'Comprehensive academic support tailored to your specific needs and requirements',
    'home.services.viewMore': 'View More Services',
    
    'home.whyChoose.title': 'Why Choose Us?',
    'home.whyChoose.subtitle': 'We combine academic expertise with professional service to deliver exceptional results that exceed expectations.',
    
    'home.testimonials.title': 'What Our Clients Say',
    'home.testimonials.subtitle': 'Real feedback from students who achieved academic success with our help',
    
    'home.cta.title': 'Ready to Excel in Your Studies?',
    'home.cta.subtitle': 'Get started today and experience the difference professional academic support can make',
    'home.cta.getQuote': 'Get Your Quote',
    'home.cta.viewServices': 'View All Services',
    
    // Services
    'services.title': 'Professional Academic Services',
    'services.subtitle': 'Comprehensive academic writing and research services designed to help you achieve excellence in your studies',
    'services.getStarted': 'Get Started Today',
    'services.ourServices': 'Our Academic Services',
    'services.chooseServices': 'Choose from our comprehensive range of academic writing and research services',
    'services.howItWorks': 'How It Works',
    'services.process.subtitle': 'Simple, transparent process to get your academic work completed',
    'services.whyStandOut': 'Why Our Services Stand Out',
    'services.standOut.subtitle': 'We deliver exceptional academic work that meets the highest standards of quality and originality.',
    'services.readyToStart': 'Ready to Get Started?',
    'services.readyToStart.subtitle': 'Contact us today to discuss your academic needs and get a personalized quote.',
    'services.getQuote': 'Get Your Quote',
    
    // About
    'about.title': 'About Thesis Assignment Hub',
    'about.subtitle': 'We are a dedicated team of academic professionals committed to helping students achieve excellence in their educational journey through high-quality writing and research services.',
    'about.workWithUs': 'Work With Us',
    'about.ukWebsite': 'UK Website',
    'about.mission.title': 'Our Mission',
    'about.mission.text1': 'To empower students worldwide by providing exceptional academic writing and research services that not only meet their immediate needs but also contribute to their long-term educational success.',
    'about.mission.text2': 'We believe that every student deserves access to high-quality academic support, regardless of their background or circumstances. Our goal is to bridge the gap between academic challenges and student success.',
    'about.mission.point1': 'Deliver original, high-quality academic work',
    'about.mission.point2': 'Support students at all educational levels',
    'about.mission.point3': 'Maintain the highest ethical standards',
    'about.mission.point4': 'Foster academic growth and learning',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide everything we do and ensure exceptional service delivery',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.description': 'We strive for the highest quality in every piece of academic work we deliver.',
    'about.values.integrity.title': 'Integrity',
    'about.values.integrity.description': 'Honest, ethical practices and complete confidentiality in all our services.',
    'about.values.collaboration.title': 'Collaboration',
    'about.values.collaboration.description': 'Working closely with students to understand and meet their unique needs.',
    'about.values.learning.title': 'Learning',
    'about.values.learning.description': 'Supporting educational growth and academic development at every level.',
    'about.team.title': 'Meet Our Expert Team',
    'about.team.subtitle': 'Dedicated professionals committed to your academic success',
    'about.quality.title': 'Quality Assurance',
    'about.quality.text': 'Every project goes through our rigorous quality assurance process to ensure it meets the highest academic standards.',
    'about.quality.point1': 'Multi-level review process',
    'about.quality.point2': 'Plagiarism detection and prevention',
    'about.quality.point3': 'Grammar and style checking',
    'about.quality.point4': 'Academic formatting verification',
    'about.excellence.title': 'Commitment to Excellence',
    'about.excellence.text1': 'Our commitment to excellence extends beyond just delivering assignments. We\'re dedicated to helping you understand the subject matter and improve your academic skills.',
    'about.excellence.text2': 'With a team of PhD-qualified writers and researchers from diverse academic backgrounds, we ensure that every project is handled by experts in the relevant field.',
    'about.excellence.viewServices': 'View Our Services',
    'about.cta.title': 'Ready to Experience Excellence?',
    'about.cta.subtitle': 'Join hundreds of students who have achieved academic success with our professional support',
    'about.cta.getStarted': 'Get Started Today',
    
    // Contact
    'contact.title': 'Get Your Academic Help Today',
    'contact.subtitle': 'Connect with our expert team for personalized academic writing solutions',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject/Topic',
    'contact.form.service': 'Service Type',
    'contact.form.pages': 'Number of Pages',
    'contact.form.deadline': 'Deadline',
    'contact.form.level': 'Academic Level',
    'contact.form.message': 'Project Details',
    'contact.form.submit': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Get in touch with us through any of these channels',
    'contact.form.additionalRequirements': 'Additional Requirements',
    'contact.form.instructionsPlaceholder': 'Please provide detailed instructions, formatting requirements, sources needed, etc.',
    'contact.form.getQuoteNow': 'Get Quote Now',
    'contact.info.email.title': 'Email Us',
    'contact.info.email.content': 'thesisassignmentsuk@gmail.com',
    'contact.info.email.description': 'Send us your requirements anytime',
    'contact.info.phone.title': 'Call Us',
    'contact.info.phone.content': '+44 7482 576463',
    'contact.info.phone.description': 'Speak with our academic consultants',
    'contact.info.hours.title': 'Business Hours',
    'contact.info.hours.content': '24/7 Available',
    'contact.info.hours.description': 'Round-the-clock support for urgent needs',
    'contact.info.location.title': 'Service Areas',
    'contact.info.location.content': 'Worldwide',
    'contact.info.location.description': 'Supporting students globally',
    'contact.guarantee.title': 'Quick Response Guarantee',
    'contact.guarantee.response': 'Response within 2 hours',
    'contact.guarantee.quote': 'Free quote and timeline',
    'contact.guarantee.noObligation': 'No obligation to proceed',
    'contact.guarantee.confidential': 'Confidential consultation',
    'contact.guarantee.support': '24/7 customer support',
    'contact.emergency.title': 'Emergency Support',
    'contact.emergency.description': 'Need urgent help with a last-minute assignment? We offer 24/7 emergency support for tight deadlines.',
    'contact.emergency.phone': '+44 7482 576463',
    'contact.emergency.label': 'Emergency Hotline',
    'contact.success.title': 'Thank You!',
    'contact.success.message': 'Your message has been received. We\'ll get back to you within 2 hours with a detailed quote and timeline.',
    'contact.success.redirect': 'Redirecting back to form in a few seconds...',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Common questions about our services and process',
    'contact.faq.q1': 'How quickly can you complete my assignment?',
    'contact.faq.a1': 'We can work with deadlines as short as 3 hours for urgent assignments. Standard delivery times range from 24 hours to several weeks, depending on complexity and length.',
    'contact.faq.q2': 'Is the work original and plagiarism-free?',
    'contact.faq.a2': 'Absolutely. All our work is written from scratch by qualified experts. We use advanced plagiarism detection tools and provide a free plagiarism report with every order.',
    'contact.faq.q3': 'What if I need revisions?',
    'contact.faq.a3': 'We offer unlimited free revisions within 30 days of delivery. Our goal is to ensure you are completely satisfied with the final work.',
    'contact.faq.q4': 'How do you ensure confidentiality?',
    'contact.faq.a4': 'We maintain strict confidentiality protocols. Your personal information and assignment details are never shared with third parties, and all communication is secure.',
    
    // Pricing
    'pricing.title': 'Transparent Pricing',
    'pricing.subtitle': 'Quality academic services at competitive prices. No hidden fees, no surprises - just honest pricing for exceptional work.',
    'pricing.discount': '🎉 New customers get 30% off their first order!',
    'pricing.calculator.title': 'Calculate Your Price',
    'pricing.calculator.subtitle': 'Get an instant estimate based on your specific requirements',
    'pricing.calculator.serviceType': 'Service Type',
    'pricing.calculator.subjectArea': 'Subject Area',
    'pricing.calculator.academicLevel': 'Academic Level',
    'pricing.calculator.deadline': 'Deadline',
    'pricing.calculator.pages': 'Number of Pages',
    'pricing.calculator.selectService': 'Select Service',
    'pricing.calculator.selectSubject': 'Select Subject',
    'pricing.calculator.selectLevel': 'Select Level',
    'pricing.calculator.selectDeadline': 'Select Deadline',
    'pricing.calculator.enterPages': 'Enter number of pages',
    'pricing.calculator.level.highSchool': 'High School',
    'pricing.calculator.level.undergraduate': 'Undergraduate',
    'pricing.calculator.level.graduate': 'Graduate/Masters',
    'pricing.calculator.level.phd': 'PhD/Doctorate',
    'pricing.calculator.estimatedPrice': 'Estimated Price',
    'pricing.calculator.disclaimer': 'This is an estimate. Final price may vary based on specific requirements.',
    'pricing.calculator.fillRequired': 'Please fill in the required fields',
    
    // Deadline options
    'pricing.calculator.deadline.24h': '24 Hours',
    'pricing.calculator.deadline.48h': '48 Hours',
    'pricing.calculator.deadline.3days': '3 Days',
    'pricing.calculator.deadline.1week': '1 Week',
    'pricing.calculator.deadline.2weeks': '2+ Weeks',
    
    'pricing.additional.title': 'Additional Services',
    'pricing.additional.subtitle': 'Enhance your order with these premium add-on services',
    'pricing.additional.rushDelivery24': 'Rush Delivery (24 hours)',
    'pricing.additional.rushDelivery48': 'Rush Delivery (48 hours)',
    'pricing.additional.rushDelivery72': 'Rush Delivery (72 hours)',
    'pricing.additional.powerpoint': 'PowerPoint Presentation',
    'pricing.additional.excel': 'Excel/Statistical Analysis',
    'pricing.additional.proofreading': 'Proofreading & Editing',
    'pricing.additional.plagiarism': 'Plagiarism Removal',
    'pricing.additional.aiRemoval': 'AI Content Removal',
    'pricing.additional.price.rush24': '+50% of base price',
    'pricing.additional.price.rush48': '+30% of base price',
    'pricing.additional.price.rush72': '+20% of base price',
    'pricing.additional.price.powerpoint': '200 per slide',
    'pricing.additional.price.excel': '375 per hour',
    'pricing.additional.price.proofreading': '125 per page',
    'pricing.additional.price.plagiarism': '200 per page',
    'pricing.additional.price.aiRemoval': '200 per page',
    'pricing.payment.title': 'Payment Methods',
    'pricing.payment.subtitle': 'We accept multiple payment methods for your convenience',
    'pricing.payment.info': 'Available Payment Options',
    'pricing.payment.description': 'Contact us to get specific payment details for your preferred method. We\'ll provide you with secure payment instructions once you\'re ready to proceed.',
    'pricing.faq.title': 'Pricing FAQ',
    'pricing.faq.subtitle': 'Common questions about our pricing and payment terms',
    'pricing.cta.title': 'Ready to Get Started?',
    'pricing.cta.subtitle': 'Contact us today for a personalized quote based on your specific requirements',
    'pricing.cta.getQuote': 'Get Your Quote',
    'pricing.cta.viewServices': 'View Services',
    
    // Offers
    'offers.title': 'Exclusive Offers',
    'offers.subtitle': 'Take advantage of our special offers and save on premium academic services. Quality education support shouldn\'t break the bank!',
    'offers.claim': 'Claim Your Offers',
    'offers.badge': 'Limited Time',
    'offers.amazing.title': 'Amazing Deals & Benefits',
    'offers.amazing.subtitle': 'We believe in providing exceptional value to our clients through these exclusive offers',
    'offers.terms.title': 'Terms & Conditions',
    'offers.terms.subtitle': 'Please read our offer terms carefully to understand how to claim these benefits',
    'offers.termsImportant': 'Important',
    'offers.cta.title': 'Don\'t Miss Out on These Amazing Offers!',
    'offers.cta.subtitle': 'Contact us today to claim your benefits and get started with premium academic services',
    'offers.cta.getStarted': 'Get Started Now',
    'offers.cta.viewServices': 'View Services',
    'offers.ctaLimited': 'Limited Time Offer',
    
    // Chatbot
    'chatbot.title': 'AI Academic Assistant',
    'chatbot.welcome': '👋 Hello! I\'m your AI academic assistant. I can help you with information about our services, pricing, placing orders, and guide you through our academic support process. What\'s your name?',
    'chatbot.thinking': 'Thinking...',
    'chatbot.poweredBy': 'AI Assistant',
    'chatbot.clearChat': 'Clear Chat',
    'chatbot.translating': 'Translating...',
    'chatbot.quickStart': 'Quick start:',
    'chatbot.error': 'I apologize, but I\'m experiencing technical difficulties. Please contact us directly via WhatsApp at +447482576463 or through our contact form for immediate assistance with your academic needs.',
    'chatbot.connectionError': 'I\'m having trouble connecting right now. Please reach out to us on WhatsApp at +447482576463 for immediate assistance!',
    'chatbot.whatsappMessage.withName': 'Hi! I\'m ${userName}. I was chatting with your AI assistant and would like to discuss my academic requirements.',
    'chatbot.whatsappMessage.default': 'Hi! I was chatting with your AI assistant and would like to discuss my academic requirements.',
    'chatbot.quickReply.services': 'What services do you offer?',
    'chatbot.quickReply.pricing': 'How much does it cost?',
    'chatbot.quickReply.freeServices': 'Tell me about FREE services',
    'chatbot.quickReply.order': 'How to place an order?',
    'chatbot.quickReply.discounts': 'Current discounts?',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.greeting': 'Hello! What\'s your name so I can assist you better?',
    'chatbot.welcomeWithName': 'Nice to meet you, {name}! How can I help you today?',
    'chatbot.services': 'We offer comprehensive academic services:\n\n• Academic Assignments\n• Thesis Writing\n• Research Papers\n• Dissertation Help\n• Essay Writing\n• Research Publication\n• Online Teaching\n• Plagiarism & AI Removal\n\nWhich service interests you most?',
    'chatbot.pricing': 'Our pricing varies based on:\n• Academic level (High School, College, Graduate)\n• Subject complexity\n• Deadline urgency\n• Number of pages\n\nWe also offer:\n• 30% off first orders\n• 30% off orders above $1000\n• Free plagiarism & AI reports\n\nWhat type of assignment do you need help with?',
    'chatbot.order': 'To place an order:\n1. Tell me your requirements\n2. Get a personalized quote\n3. Confirm and make payment\n4. Receive your completed work\n\nWhat subject is your assignment in?',
    'chatbot.free': 'Our FREE services include:\n• Plagiarism & AI detection reports\n• Assignment guidance consultation\n• Research proposal (up to 1 page)\n• Unlimited revisions on paid work\n\nThese are always included at no extra cost! Would you like to know more about any specific service?',
    'chatbot.discounts': 'Current offers:\n• 30% OFF first order for new clients\n• 30% OFF orders above $1000\n• FREE plagiarism & AI reports\n• FREE research proposals\n• Unlimited FREE revisions\n\nReady to get started with your first order?',
    'chatbot.serviceSelected': 'Great choice! {service} is one of our most popular services. To give you an accurate quote, I need a few details:\n\n• How many pages do you need?\n• What\'s your deadline?\n• What academic level?\n\nOr would you like me to connect you with our team for a detailed consultation?',
    'chatbot.connect': 'Perfect! I\'ve notified our professional team about your inquiry{name}. They will contact you shortly with personalized assistance.\n\nFor faster service, please visit our contact page and provide your details. Is there anything else I can help you with?',
    'chatbot.levels': 'We support all academic levels:\n• High School - 300/page\n• Undergraduate - 450/page\n• Graduate/Masters - 625/page\n• PhD/Doctorate - 875/page\n\nPrices may vary based on subject complexity and deadline. What level do you need help with?',
    'chatbot.deadlines': 'We handle various deadlines:\n• 24 hours (+50% rush fee)\n• 48 hours (+30% rush fee)\n• 3-7 days (standard rates)\n• 1+ weeks (best rates)\n\nWhat\'s your deadline?',
    'chatbot.default': 'I\'d be happy to help you{name}! I can provide information about our services, pricing, discounts, and help you place an order. What would you like to know more about?',
    
    // Offers Items
    'offers.freePlagiarism.title': 'Free Plagiarism & AI Reports',
    'offers.freePlagiarism.desc': 'Get comprehensive plagiarism and AI detection reports with every order at no extra cost.',
    'offers.freePlagiarism.highlight': 'Always Free',
    'offers.freePlagiarism.feature1': 'Detailed plagiarism report',
    'offers.freePlagiarism.feature2': 'AI content detection',
    'offers.freePlagiarism.feature3': 'Originality verification',
    'offers.freePlagiarism.feature4': 'Quality assurance',
    
    'offers.freeGuidance.title': 'Free Assignment Guidance',
    'offers.freeGuidance.desc': 'Receive expert guidance and consultation for your assignments before placing an order.',
    'offers.freeGuidance.highlight': 'Complimentary',
    'offers.freeGuidance.feature1': 'Topic consultation',
    'offers.freeGuidance.feature2': 'Structure guidance',
    'offers.freeGuidance.feature3': 'Resource recommendations',
    'offers.freeGuidance.feature4': 'Approach suggestions',
    
    'offers.freeResearch.title': 'Free Research Proposal',
    'offers.freeResearch.desc': 'Get a complete research proposal up to 1 page absolutely free to kickstart your research.',
    'offers.freeResearch.highlight': 'Up to 1 Page Free',
    'offers.freeResearch.feature1': 'Problem statement',
    'offers.freeResearch.feature2': 'Research objectives',
    'offers.freeResearch.feature3': 'Methodology outline',
    'offers.freeResearch.feature4': 'Literature overview',
    
    'offers.firstOrder.title': '25% Off First Order',
    'offers.firstOrder.desc': 'New clients get an exclusive 25% discount on their first order with us.',
    'offers.firstOrder.highlight': '25% Discount',
    'offers.firstOrder.feature1': 'Valid for new customers',
    'offers.firstOrder.feature2': 'All services included',
    'offers.firstOrder.feature3': 'No minimum order',
    'offers.firstOrder.feature4': 'One-time offer',
    
    'offers.bulkOrder.title': '20% Off Orders Above PKR 50000',
    'offers.bulkOrder.desc': 'Save big on large orders with our bulk discount for orders exceeding PKR 50000.',
    'offers.bulkOrder.highlight': 'Bulk Savings',
    'offers.bulkOrder.feature1': 'Automatic discount',
    'offers.bulkOrder.feature2': 'All services eligible',
    'offers.bulkOrder.feature3': 'Stackable with other offers',
    'offers.bulkOrder.feature4': 'No expiry date',
    
    'offers.revisions.title': 'Unlimited Revisions',
    'offers.revisions.desc': 'Get unlimited free revisions on all paid tasks until you are completely satisfied.',
    'offers.revisions.highlight': 'Always Included',
    'offers.revisions.feature1': 'No revision limits',
    'offers.revisions.feature2': 'Free of charge',
    'offers.revisions.feature3': '30-day guarantee',
    'offers.revisions.feature4': 'Quality assurance',
    
    'offers.claimNow': 'Claim Now',
    'offers.termsGeneral': 'General Terms',
    'offers.termsGeneral.term1': 'All offers are subject to availability and may be modified or discontinued at any time',
    'offers.termsGeneral.term2': 'Offers cannot be combined unless explicitly stated',
    'offers.termsGeneral.term3': 'Free services are provided as-is and subject to our standard quality guidelines',
    'offers.termsDiscount': 'Discount Terms',
    'offers.termsDiscount.term1': 'First-time customer discount applies only to new clients who haven\'t used our services before',
    'offers.termsDiscount.term2': 'Bulk discount for orders above PKR 50000 is automatically applied at checkout',
    'offers.termsDiscount.term3': 'Discounts are calculated before taxes and additional fees',
    'offers.termsRevision': 'Revision Policy',
    'offers.termsRevision.term1': 'Unlimited revisions are available for 30 days after delivery',
    'offers.termsRevision.term2': 'Revisions must be within the original scope of work',
    'offers.termsRevision.term3': 'Major changes to requirements may incur additional charges',
    
    // Subject Names
    'subject.business': 'Business & Management',
    'subject.computerScience': 'Computer Science',
    'subject.engineering': 'Engineering',
    'subject.literature': 'Literature & English',
    'subject.psychology': 'Psychology',
    'subject.sociology': 'Sociology',
    'subject.history': 'History',
    'subject.mathematics': 'Mathematics',
    'subject.science': 'Science',
    'subject.law': 'Law',
    'subject.medicine': 'Medicine',
    'subject.technology': 'Technology',
    'subject.finance': 'Finance',
    'subject.education': 'Education',
    'subject.healthcare': 'Healthcare',
    'subject.management': 'Management',
    'subject.socialSciences': 'Social Sciences',
    'subject.philosophy': 'Philosophy',
    'subject.other': 'Other',
    
    // Team Roles
    'team.academicDirector': 'Academic Director',
    'team.researchSpecialist': 'Research Specialist',
    'team.writingCoordinator': 'Writing Coordinator',
    'team.director': 'Director',
    'team.itManager': 'IT Manager',
    'team.marketingSalesManager': 'Marketing & Sales Manager',
    'team.experience.sarah': '12+ years',
    'team.experience.james': '15+ years',
    'team.experience.maria': '10+ years',
    'team.experience.director': '15+ years',
    'team.experience.itManager': '8+ years',
    'team.experience.raja': '7+ years',
    'team.literatureHumanities': 'Literature & Humanities',
    'team.sciencesTechnology': 'Sciences & Technology',
    'team.businessStrategy': 'Business Strategy & Leadership',
    'team.technologyManagement': 'Technology Management & Infrastructure',
    'team.marketingAndSales': 'Marketing, Sales & Customer Relations',
    
    // Samples
    'samples.title': 'Sample Works',
    'samples.subtitle': 'Explore our collection of high-quality academic samples across various subjects and formats',
    'samples.viewSamples': 'View Sample Categories',
    'samples.categories.title': 'Sample Categories',
    'samples.categories.subtitle': 'Browse through our diverse collection of academic samples organized by type and subject',
    'samples.benefits.title': 'Why View Our Samples?',
    'samples.benefits.subtitle': 'Understanding quality through examples helps you make informed decisions',
    'samples.explore.title': 'Ready to Explore?',
    'samples.explore.subtitle': 'Browse through our samples to understand the quality and style of our academic work',
    'samples.explore.browse': 'Browse All Samples',
    'samples.explore.getStarted': 'Get Started with Your Order',
    
    // Sample Categories
    'samples.category.essays': 'Essays',
    'samples.category.researchPapers': 'Research Papers',
    'samples.category.thesis': 'Thesis Samples',
    'samples.category.caseStudies': 'Case Studies',
    'samples.category.dissertations': 'Dissertations',
    'samples.category.reports': 'Reports',
    'samples.category.essays.desc': 'Argumentative, narrative, descriptive, and analytical essays across various subjects.',
    'samples.category.researchPapers.desc': 'Comprehensive research papers with proper methodology and citations.',
    'samples.category.thesis.desc': 'Complete thesis examples from various academic levels and disciplines.',
    'samples.category.caseStudies.desc': 'Detailed case study analyses across different industries and subjects.',
    'samples.category.dissertations.desc': 'Comprehensive dissertation samples with complete chapters and analysis.',
    'samples.category.reports.desc': 'Professional reports including lab reports, business reports, and project reports.',
    'samples.category.count': 'Samples',
    
    // Sample Featured
    'samples.featured.socialMedia.title': 'The Impact of Social Media on Modern Communication',
    'samples.featured.socialMedia.type': 'Research Paper',
    'samples.featured.socialMedia.subject': 'Communication Studies',
    'samples.featured.socialMedia.desc': 'A comprehensive analysis of how social media platforms have transformed interpersonal communication patterns in the digital age.',
    'samples.featured.business.title': 'Sustainable Business Practices in the 21st Century',
    'samples.featured.business.type': 'Case Study',
    'samples.featured.business.subject': 'Business Management',
    'samples.featured.business.desc': 'An in-depth case study examining how modern corporations integrate sustainability into their business models.',
    'samples.featured.climate.title': 'Climate Change and Its Economic Implications',
    'samples.featured.climate.type': 'Thesis',
    'samples.featured.climate.subject': 'Environmental Economics',
    'samples.featured.climate.desc': 'A detailed thesis exploring the economic costs and benefits of climate change mitigation strategies.',
    'samples.featured.aiHealthcare.title': 'AI in Healthcare Predictive Analytics for Heart Diseases',
    'samples.featured.aiHealthcare.type': 'Proposal',
    'samples.featured.aiHealthcare.subject': 'Healthcare Technology',
    'samples.featured.aiHealthcare.desc': 'A comprehensive research proposal exploring the applications of artificial intelligence in predictive analytics for heart disease detection and prevention.',
    'samples.featured.aiWeather.title': 'AI in Weather Prediction Using Satellite Images',
    'samples.featured.aiWeather.type': 'Research Paper',
    'samples.featured.aiWeather.subject': 'Computer Science',
    'samples.featured.aiWeather.desc': 'Advanced research on utilizing artificial intelligence and satellite imagery for accurate weather prediction and climate modeling.',
    'samples.featured.pythonProblem.title': 'Python for Real-World Problem Solving',
    'samples.featured.pythonProblem.type': 'Assignment',
    'samples.featured.pythonProblem.subject': 'Computer Programming',
    'samples.featured.pythonProblem.desc': 'Practical assignment demonstrating Python programming skills through real-world problem-solving applications and implementations.',
    'samples.level.graduate': 'Graduate',
    'samples.level.mba': 'MBA',
    'samples.level.masters': 'Masters',
    'samples.level.phd': 'PhD',
    'samples.level.undergraduate': 'Undergraduate',
    'samples.pages': 'pages',
    'samples.viewSample': 'View Sample',
    'samples.request': 'Request',
    'samples.requestSamples': 'Request Samples',
    'samples.requestSampleAccess': 'Request Sample Access',
    'samples.availableSubjects': 'Available Subjects',
    'samples.subject': 'Subject',
    'samples.featuredTitle': 'Featured Sample Works',
    'samples.featuredSubtitle': 'Preview some of our high-quality academic works across different disciplines',
    'samples.howToAccess.title': 'How to Access Sample Works',
    'samples.howToAccess.subtitle': 'Follow these simple steps to get access to our comprehensive sample library',
    'samples.step.contact.title': 'Contact Us',
    'samples.step.contact.desc': 'Reach out to us through our contact form or direct communication channels.',
    'samples.step.specify.title': 'Specify Requirements',
    'samples.step.specify.desc': 'Tell us what type of samples you need - subject, academic level, and format.',
    'samples.step.receive.title': 'Receive Samples',
    'samples.step.receive.desc': 'Get access to relevant sample works organized in easy-to-navigate folders.',
    'samples.quality.title': 'Why Our Samples Stand Out',
    'samples.quality.subtitle': 'Our sample works represent the same high standards and quality that we deliver to all our clients.',
    'samples.quality.benefit1': 'Written by PhD-qualified experts',
    'samples.quality.benefit2': 'Properly formatted and cited',
    'samples.quality.benefit3': 'Original and plagiarism-free',
    'samples.quality.benefit4': 'Comprehensive research and analysis',
    'samples.quality.benefit5': 'Multiple academic levels covered',
    'samples.quality.benefit6': 'Diverse subject areas included',
    'samples.note': 'Sample works will be provided in folder format upon request. Contact us to access our complete sample library.',
    'samples.demo': 'This is a demonstration sample. Contact us for full access to our sample library.',
    'samples.readOnly': 'Sample Document - Read Only',
    
    // Footer
    'footer.description': 'Providing exceptional academic writing services to help students excel in their educational journey. Quality, reliability, and academic excellence are our top priorities.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.copyright': '© 2024 Thesis Assignment Hub. All rights reserved.',
    
    // Common
    'common.free': 'FREE',
    'common.getQuote': 'Get Quote',
    'common.learnMore': 'Learn More',
    'common.contactUs': 'Contact Us',
    'common.viewAll': 'View All',
    'common.readMore': 'Read More',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.minimize': 'Minimize',
    'common.maximize': 'Maximize',
    'common.viewPricing': 'View Pricing',
    'common.support': 'Support',
    'common.original': 'Original',
    'common.satisfaction': 'Satisfaction',
    'common.rating': 'Rating',
    
    // WhatsApp Widget
    'whatsapp.contactButton': 'Contact us on WhatsApp',
    'whatsapp.modalTitle': 'WhatsApp Message',
    'whatsapp.modalSubtitle': 'Send us a message',
    'whatsapp.messageLabel': 'Your Message',
    'whatsapp.messagePlaceholder': 'Type your message here...',
    'whatsapp.description': 'We\'ll receive your message on WhatsApp and get back to you as soon as possible.',
    'whatsapp.cancel': 'Cancel',
    'whatsapp.send': 'Send',
    
    // Service Features
    'feature.academicAssignments': 'Academic Assignments',
    'feature.thesisWriting': 'Thesis Writing',
    'feature.researchPapers': 'Research Papers',
    'feature.dissertationHelp': 'Dissertation Help',
    'feature.essayWriting': 'Essay Writing',
    'feature.researchPublication': 'Research Publication in Journals',
    'feature.onlineTeaching': 'Online Teaching',
    'feature.plagiarismRemoval': 'Plagiarism & AI Removal',
    'feature.paperPreparation': 'Paper Preparation',
    'feature.researchProposal': 'Research Proposal',
    'feature.other': 'Other',
    
    // Service Descriptions
    'service.academicAssignments.desc': 'Comprehensive help with essays, reports, case studies, and all types of academic assignments.',
    'service.thesisWriting.desc': 'Expert assistance with thesis writing from proposal development to final submission.',
    'service.researchPapers.desc': 'In-depth research papers with comprehensive analysis and academic rigor.',
    'service.dissertationHelp.desc': 'Complete dissertation support from topic selection to final defense preparation.',
    'service.essayWriting.desc': 'Professional essay writing services for all academic levels and subjects.',
    'service.researchProposal.desc': 'Well-structured research proposals that get approved by academic committees.',
    'service.researchPublication.desc': 'Professional support for publishing your research in reputable academic journals.',
    'service.onlineTeaching.desc': 'Personalized online tutoring and assignment guidance sessions.',
    'service.plagiarismRemoval.desc': 'Professional service to remove plagiarism and AI-generated content from your work.',
    'service.paperPreparation.desc': 'Complete paper preparation service including formatting, citations, and final review.',
    'service.freePlagiarism.title': 'Free Plagiarism & AI Reports',
    'service.freePlagiarism.desc': 'Get comprehensive plagiarism and AI detection reports with every order at no extra cost.',
    'service.freeGuidance.title': 'Free Assignment Guidance',
    'service.freeGuidance.desc': 'Receive expert guidance and consultation for your assignments before placing an order.',
    
    // Service Pricing
    'service.pricing.custom': 'Custom pricing based on requirements',
    'service.pricing.tailored': 'Tailored pricing for comprehensive thesis support',
    'service.pricing.competitive': 'Competitive rates based on complexity and length',
    'service.pricing.comprehensive': 'Comprehensive packages available',
    'service.pricing.affordable': 'Affordable rates starting from basic level',
    'service.pricing.premium': 'Premium service with publication guarantee',
    'service.pricing.hourly': 'Hourly rates with flexible scheduling',
    'service.pricing.perPage': 'Competitive per-page pricing',
    'service.pricing.formatting': 'Affordable formatting and preparation rates',
    
    // Service Features
    'service.feature.allLevels': 'All academic levels',
    'service.feature.variousSubjects': 'Various subjects',
    'service.feature.originalContent': 'Original content',
    'service.feature.properFormatting': 'Proper formatting',
    'service.feature.researchProposal': 'Research proposal',
    'service.feature.literatureReview': 'Literature review',
    'service.feature.methodologyDesign': 'Methodology design',
    'service.feature.dataAnalysis': 'Data analysis',
    'service.feature.originalResearch': 'Original research',
    'service.feature.peerReviewReady': 'Peer review ready',
    'service.feature.citationIncluded': 'Citation included',
    'service.feature.qualitySources': 'Quality sources',
    'service.feature.topicSelection': 'Topic selection',
    'service.feature.chapterWiseWriting': 'Chapter-wise writing',
    'service.feature.defensePreparation': 'Defense preparation',
    'service.feature.revisionSupport': 'Revision support',
    'service.feature.argumentativeEssays': 'Argumentative essays',
    'service.feature.narrativeEssays': 'Narrative essays',
    'service.feature.descriptiveEssays': 'Descriptive essays',
    'service.feature.compareContrast': 'Compare & contrast',
    'service.feature.problemStatement': 'Problem statement',
    'service.feature.literatureGap': 'Literature gap',
    'service.feature.methodology': 'Methodology',
    'service.feature.timeline': 'Timeline',
    'service.feature.journalSelection': 'Journal selection',
    'service.feature.manuscriptPreparation': 'Manuscript preparation',
    'service.feature.peerReviewSupport': 'Peer review support',
    'service.feature.publicationGuidance': 'Publication guidance',
    'service.feature.oneOnOneSessions': 'One-on-one sessions',
    'service.feature.assignmentWalkthrough': 'Assignment walkthrough',
    'service.feature.conceptClarification': 'Concept clarification',
    'service.feature.studyGuidance': 'Study guidance',
    'service.feature.contentRewriting': 'Content rewriting',
    'service.feature.originalityEnhancement': 'Originality enhancement',
    'service.feature.qualityImprovement': 'Quality improvement',
    'service.feature.reportIncluded': 'Report included',
    'service.feature.academicFormatting': 'Academic formatting',
    'service.feature.citationStyles': 'Citation styles',
    'service.feature.proofreading': 'Proofreading',
    'service.feature.finalReview': 'Final review',
    'service.feature.detailedReport': 'Detailed plagiarism report',
    'service.feature.aiDetection': 'AI content detection',
    'service.feature.originalityVerification': 'Originality verification',
    'service.feature.qualityAssurance': 'Quality assurance',
    'service.feature.topicConsultation': 'Topic consultation',
    'service.feature.structureGuidance': 'Structure guidance',
    'service.feature.resourceRecommendations': 'Resource recommendations',
    'service.feature.approachSuggestions': 'Approach suggestions',
    
    'service.freeService': 'FREE SERVICE',
    'service.getFreeService': 'Get Free Service',
    
    // Stats
    'stats.projectsCompleted': 'Projects Completed',
    'stats.clientSatisfaction': 'Client Satisfaction',
    'stats.supportAvailable': 'Support Available',
    'stats.yearsExperience': 'Years Experience',
    'stats.expertWriters': 'Expert Writers',
    
    // Home Page Service Descriptions
    'home.service.academicAssignments.desc': 'Comprehensive help with all types of academic assignments across various subjects.',
    'home.service.thesisWriting.desc': 'Expert assistance in thesis writing, from proposal to final submission.',
    'home.service.researchPublication.desc': 'Professional support for publishing your research in reputable academic journals.',
    
    // Home Page Testimonials
    'home.testimonial.sarah.name': 'Sarah Johnson',
    'home.testimonial.sarah.role': 'Graduate Student',
    'home.testimonial.sarah.content': 'The quality of work exceeded my expectations. My thesis was completed on time and with exceptional research depth.',
    'home.testimonial.michael.name': 'Michael Chen',
    'home.testimonial.michael.role': 'PhD Candidate',
    'home.testimonial.michael.content': 'Professional service with excellent communication throughout the process. Highly recommend for research work.',
    'home.testimonial.emma.name': 'Emma Davis',
    'home.testimonial.emma.role': 'Undergraduate',
    'home.testimonial.emma.content': 'Helped me understand complex concepts while delivering high-quality assignments. Great learning experience.',
    
    // Services Page Process Steps
    'services.process.step1.title': 'Submit Requirements',
    'services.process.step1.desc': 'Share your assignment details, guidelines, and deadline with us.',
    'services.process.step2.title': 'Get Quote',
    'services.process.step2.desc': 'Receive a competitive quote based on your specific requirements.',
    'services.process.step3.title': 'Expert Assignment',
    'services.process.step3.desc': 'Your work is assigned to a qualified expert in your subject area.',
    'services.process.step4.title': 'Quality Delivery',
    'services.process.step4.desc': 'Receive your completed work on time with unlimited revisions.',
    
    // Pricing FAQ
    'pricing.faq.q1': 'How is the final price calculated?',
    'pricing.faq.a1': 'The final price is based on academic level, number of pages, deadline, and any additional services. We provide a detailed quote before you confirm your order.',
    'pricing.faq.q2': 'Are there any hidden fees?',
    'pricing.faq.a2': 'No, we believe in transparent pricing. The quote you receive includes all costs except for optional add-on services that you specifically request.',
    'pricing.faq.q3': 'Do you offer discounts for bulk orders?',
    'pricing.faq.a3': 'Yes! Orders above 25,000 automatically receive a 30% discount. We also offer special rates for long-term clients and repeat customers.',
    'pricing.faq.q4': 'What payment methods do you accept?',
    'pricing.faq.a4': 'We accept various payment methods including major credit cards, digital wallets, and international transfer services. Contact us for specific payment details.',
    'pricing.faq.q5': 'Is there a refund policy?',
    'pricing.faq.a5': 'Yes, we offer a comprehensive refund policy. If you\'re not satisfied with the work, we provide unlimited free revisions or a full refund in qualifying cases.',
    
    // Home Page Why Choose Us Benefits
    'home.benefit.expertWriters': 'Expert writers with advanced degrees',
    'home.benefit.freePlagiarism': 'Free plagiarism and AI reports',
    'home.benefit.freeRevisions': 'Unlimited free revisions',
    'home.benefit.timelyDelivery': 'Timely delivery guaranteed',
    'home.benefit.support247': '24/7 customer support available',
    'home.benefit.confidential': 'Confidential and secure service',
    
    // Home Page Rating Section
    'home.rating.title': '4.9/5 Rating',
    'home.rating.subtitle': 'From 500+ satisfied clients',
    'home.rating.expertTeam': 'Expert Team',
    'home.rating.qualityAssured': 'Quality Assured',
    
    // Services Page Features
    'services.feature.onTimeDelivery.title': 'On-Time Delivery',
    'services.feature.onTimeDelivery.desc': 'Never miss a deadline',
    'services.feature.qualityGuaranteed.title': 'Quality Guaranteed',
    'services.feature.qualityGuaranteed.desc': 'High academic standards',
    'services.feature.originalWork.title': 'Original Work',
    'services.feature.originalWork.desc': 'Plagiarism-free content',
    'services.feature.expertWriters.title': 'Expert Writers',
    'services.feature.expertWriters.desc': 'PhD qualified professionals',
  },
  ar: {
    // Currency
    'currency.pkr': 'ر.س',
    
    // Units
    'unit.page': 'ورقة',
    'unit.pages': 'أوراق',
    'unit.per': 'لكل',
    'unit.average': 'متوسط',
    
    // Header/Navigation
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.offers': 'العروض',
    'nav.samples': 'النماذج',
    'nav.pricing': 'الأسعار',
    'nav.about': 'حولنا',
    'nav.contact': 'اتصل بنا',
    'nav.getStarted': 'ابدأ الآن',
    
    // Home Page
    'home.hero.title': 'تفوق في رحلتك الأكاديمية',
    'home.hero.subtitle': 'تمكين البحث، تحقيق النجاح',
    'home.hero.viewServices': 'عرض الخدمات',
    'home.hero.getQuote': 'احصل على عرض سعر',
    
    'home.services.title': 'خدماتنا الأكاديمية',
    'home.services.subtitle': 'دعم أكاديمي شامل مصمم خصيصاً لتلبية احتياجاتك ومتطلباتك المحددة',
    'home.services.viewMore': 'عرض المزيد من الخدمات',
    
    'home.whyChoose.title': 'لماذا تختارنا؟',
    'home.whyChoose.subtitle': 'نحن نجمع بين الخبرة الأكاديمية والخدمة المهنية لتقديم نتائج استثنائية تفوق التوقعات.',
    
    'home.testimonials.title': 'ماذا يقول عملاؤنا',
    'home.testimonials.subtitle': 'تعليقات حقيقية من الطلاب الذين حققوا النجاح الأكاديمي بمساعدتنا',
    
    'home.cta.title': 'هل أنت مستعد للتفوق في دراستك؟',
    'home.cta.subtitle': 'ابدأ اليوم واختبر الفرق الذي يمكن أن يحدثه الدعم الأكاديمي المهني',
    'home.cta.getQuote': 'احصل على عرض سعر',
    'home.cta.viewServices': 'عرض جميع الخدمات',
    
    // Services
    'services.title': 'الخدمات الأكاديمية المهنية',
    'services.subtitle': 'خدمات شاملة للكتابة الأكاديمية والبحث العلمي مصممة لمساعدتك على تحقيق التميز في دراستك',
    'services.getStarted': 'ابدأ اليوم',
    'services.ourServices': 'خدماتنا الأكاديمية',
    'services.chooseServices': 'اختر من مجموعتنا الشاملة من خدمات الكتابة الأكاديمية والبحث العلمي',
    'services.howItWorks': 'كيف يعمل',
    'services.process.subtitle': 'عملية بسيطة وشفافة لإنجاز عملك الأكاديمي',
    'services.whyStandOut': 'لماذا تتميز خدماتنا',
    'services.standOut.subtitle': 'نقدم عملاً أكاديمياً استثنائياً يلبي أعلى معايير الجودة والأصالة.',
    'services.readyToStart': 'مستعد للبدء؟',
    'services.readyToStart.subtitle': 'اتصل بنا اليوم لمناقشة احتياجاتك الأكاديمية والحصول على عرض سعر مخصص.',
    'services.getQuote': 'احصل على عرض سعر',
    
    // About
    'about.title': 'حول Thesis Assignment Hub',
    'about.subtitle': 'نحن فريق متخصص من المهنيين الأكاديميين ملتزمون بمساعدة الطلاب على تحقيق التميز في رحلتهم التعليمية من خلال خدمات الكتابة والبحث عالية الجودة.',
    'about.workWithUs': 'اعمل معنا',
    'about.ukWebsite': 'الموقع البريطاني',
    'about.mission.title': 'مهمتنا',
    'about.mission.text1': 'تمكين الطلاب في جميع أنحاء العالم من خلال تقديم خدمات استثنائية للكتابة الأكاديمية والبحث العلمي التي لا تلبي احتياجاتهم الفورية فحسب، بل تساهم أيضاً في نجاحهم التعليمي طويل المدى.',
    'about.mission.text2': 'نحن نؤمن بأن كل طالب يستحق الوصول إلى دعم أكاديمي عالي الجودة، بغض النظر عن خلفيته أو ظروفه. هدفنا هو سد الفجوة بين التحديات الأكاديمية ونجاح الطلاب.',
    'about.mission.point1': 'تقديم عمل أكاديمي أصلي وعالي الجودة',
    'about.mission.point2': 'دعم الطلاب في جميع المستويات التعليمية',
    'about.mission.point3': 'الحفاظ على أعلى المعايير الأخلاقية',
    'about.mission.point4': 'تعزيز النمو الأكاديمي والتعلم',
    'about.values.title': 'قيمنا الأساسية',
    'about.values.subtitle': 'المبادئ التي توجه كل ما نقوم به وتضمن تقديم خدمة استثنائية',
    'about.values.excellence.title': 'التميز',
    'about.values.excellence.description': 'نسعى جاهدين لتحقيق أعلى جودة في كل عمل أكاديمي نقدمه.',
    'about.values.integrity.title': 'النزاهة',
    'about.values.integrity.description': 'ممارسات صادقة وأخلاقية وسرية تامة في جميع خدماتنا.',
    'about.values.collaboration.title': 'التعاون',
    'about.values.collaboration.description': 'العمل عن كثب مع الطلاب لفهم احتياجاتهم الفريدة وتلبيتها.',
    'about.values.learning.title': 'التعلم',
    'about.values.learning.description': 'دعم النمو التعليمي والتطوير الأكاديمي في كل مستوى.',
    'about.team.title': 'تعرف على فريقنا من الخبراء',
    'about.team.subtitle': 'محترفون متفانون ملتزمون بنجاحك الأكاديمي',
    'about.quality.title': 'ضمان الجودة',
    'about.quality.text': 'يخضع كل مشروع لعملية ضمان الجودة الصارمة لدينا لضمان أنه يلبي أعلى المعايير الأكاديمية.',
    'about.quality.point1': 'عملية مراجعة متعددة المستويات',
    'about.quality.point2': 'اكتشاف ومنع السرقة الأدبية',
    'about.quality.point3': 'فحص القواعد والأسلوب',
    'about.quality.point4': 'التحقق من التنسيق الأكاديمي',
    'about.excellence.title': 'الالتزام بالتميز',
    'about.excellence.text1': 'التزامنا بالتميز يتجاوز مجرد تسليم المهام. نحن مكرسون لمساعدتك على فهم المادة العلمية وتحسين مهاراتك الأكاديمية.',
    'about.excellence.text2': 'مع فريق من الكتاب والباحثين المؤهلين بدرجة الدكتوراه من خلفيات أكاديمية متنوعة، نضمن أن كل مشروع يتم التعامل معه من قبل خبراء في المجال ذي الصلة.',
    'about.excellence.viewServices': 'عرض خدماتنا',
    'about.cta.title': 'مستعد لتجربة التميز؟',
    'about.cta.subtitle': 'انضم إلى مئات الطلاب الذين حققوا النجاح الأكاديمي بدعمنا المهني',
    'about.cta.getStarted': 'ابدأ اليوم',
    
    // Contact
    'contact.title': 'احصل على مساعدتك الأكاديمية اليوم',
    'contact.subtitle': 'تواصل مع فريقنا من الخبراء للحصول على حلول كتابة أكاديمية مخصصة',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.subject': 'الموضوع/العنوان',
    'contact.form.service': 'نوع الخدمة',
    'contact.form.pages': 'عدد الصفحات',
    'contact.form.deadline': 'الموعد النهائي',
    'contact.form.level': 'المستوى الأكاديمي',
    'contact.form.message': 'تفاصيل المشروع',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.subtitle': 'تواصل معنا من خلال أي من هذه القنوات',
    'contact.form.additionalRequirements': 'متطلبات إضافية',
    'contact.form.instructionsPlaceholder': 'يرجى تقديم تعليمات مفصلة، متطلبات التنسيق، المصادر المطلوبة، إلخ.',
    'contact.form.getQuoteNow': 'احصل على عرض سعر الآن',
    'contact.info.email.title': 'راسلنا',
    'contact.info.email.content': 'thesisassignmentsuk@gmail.com',
    'contact.info.email.description': 'أرسل لنا متطلباتك في أي وقت',
    'contact.info.phone.title': 'اتصل بنا',
    'contact.info.phone.content': '+44 7482 576463',
    'contact.info.phone.description': 'تحدث مع مستشارينا الأكاديميين',
    'contact.info.hours.title': 'ساعات العمل',
    'contact.info.hours.content': 'متاح على مدار الساعة',
    'contact.info.hours.description': 'دعم مستمر للاحتياجات العاجلة',
    'contact.info.location.title': 'مناطق الخدمة',
    'contact.info.location.content': 'عالميًا',
    'contact.info.location.description': 'دعم الطلاب في جميع أنحاء العالم',
    'contact.guarantee.title': 'ضمان الاستجابة السريعة',
    'contact.guarantee.response': 'استجابة خلال ساعتين',
    'contact.guarantee.quote': 'عرض سعر مجاني وجدول زمني',
    'contact.guarantee.noObligation': 'لا التزام بالمتابعة',
    'contact.guarantee.confidential': 'استشارة سرية',
    'contact.guarantee.support': 'دعم العملاء على مدار الساعة',
    'contact.emergency.title': 'الدعم الطارئ',
    'contact.emergency.description': 'تحتاج مساعدة عاجلة في مهمة في اللحظة الأخيرة؟ نحن نقدم دعم طارئ على مدار الساعة للمواعيد النهائية الضيقة.',
    'contact.emergency.phone': '+44 7482 576463',
    'contact.emergency.label': 'الخط الساخن للطوارئ',
    'contact.success.title': 'شكرًا لك!',
    'contact.success.message': 'تم استلام رسالتك. سنعود إليك خلال ساعتين بعرض سعر مفصل وجدول زمني.',
    'contact.success.redirect': 'إعادة التوجيه إلى النموذج خلال ثوانٍ قليلة...',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.subtitle': 'أسئلة شائعة حول خدماتنا وعمليتنا',
    'contact.faq.q1': 'كم من الوقت يمكنكم إنجاز مهمتي؟',
    'contact.faq.a1': 'يمكننا العمل مع مواعيد نهائية قصيرة تصل إلى 3 ساعات للمهام العاجلة. أوقات التسليم المعيارية تتراوح من 24 ساعة إلى عدة أسابيع، حسب التعقيد والطول.',
    'contact.faq.q2': 'هل العمل أصلي وخالٍ من الانتحال؟',
    'contact.faq.a2': 'بالطبع. جميع أعمالنا مكتوبة من الصفر بواسطة خبراء مؤهلين. نستخدم أدوات متقدمة لكشف الانتحال ونقدم تقرير انتحال مجاني مع كل طلب.',
    'contact.faq.q3': 'ماذا لو احتجت إلى تعديلات؟',
    'contact.faq.a3': 'نقدم تعديلات مجانية غير محدودة خلال 30 يومًا من التسليم. هدفنا هو ضمان رضاك التام عن العمل النهائي.',
    'contact.faq.q4': 'كيف تضمنون السرية؟',
    'contact.faq.a4': 'نحافظ على بروتوكولات سرية صارمة. معلوماتك الشخصية وتفاصيل المهمة لا يتم مشاركتها مع أطراف ثالثة، وجميع الاتصالات آمنة.',
    
    // Pricing
    'pricing.title': 'أسعار شفافة',
    'pricing.subtitle': 'خدمات أكاديمية عالية الجودة بأسعار تنافسية. لا توجد رسوم مخفية، لا مفاجآت - فقط أسعار صادقة لعمل استثنائي.',
    'pricing.discount': '🎉 العملاء الجدد يحصلون على خصم 30% على طلبهم الأول!',
    'pricing.calculator.title': 'احسب سعرك',
    'pricing.calculator.subtitle': 'احصل على تقدير فوري بناءً على متطلباتك المحددة',
    'pricing.calculator.serviceType': 'نوع الخدمة',
    'pricing.calculator.subjectArea': 'مجال الموضوع',
    'pricing.calculator.academicLevel': 'المستوى الأكاديمي',
    'pricing.calculator.deadline': 'الموعد النهائي',
    'pricing.calculator.pages': 'عدد الصفحات',
    'pricing.calculator.selectService': 'اختر الخدمة',
    'pricing.calculator.selectSubject': 'اختر الموضوع',
    'pricing.calculator.selectLevel': 'اختر المستوى',
    'pricing.calculator.selectDeadline': 'اختر الموعد النهائي',
    'pricing.calculator.enterPages': 'أدخل عدد الصفحات',
    'pricing.calculator.level.highSchool': 'المدرسة الثانوية',
    'pricing.calculator.level.undergraduate': 'البكالوريوس',
    'pricing.calculator.level.graduate': 'الماجستير',
    'pricing.calculator.level.phd': 'الدكتوراه',
    'pricing.calculator.estimatedPrice': 'السعر المقدر',
    'pricing.calculator.disclaimer': 'هذا تقدير. قد يختلف السعر النهائي بناءً على المتطلبات المحددة.',
    'pricing.calculator.fillRequired': 'يرجى ملء الحقول المطلوبة',
    
    // Deadline options
    'pricing.calculator.deadline.24h': '24 ساعة',
    'pricing.calculator.deadline.48h': '48 ساعة',
    'pricing.calculator.deadline.3days': '3 أيام',
    'pricing.calculator.deadline.1week': 'أسبوع واحد',
    'pricing.calculator.deadline.2weeks': 'أسبوعان أو أكثر',
    
    'pricing.additional.title': 'خدمات إضافية',
    'pricing.additional.subtitle': 'عزز طلبك بهذه الخدمات الإضافية المتميزة',
    'pricing.additional.rushDelivery24': 'التسليم السريع (24 ساعة)',
    'pricing.additional.rushDelivery48': 'التسليم السريع (48 ساعة)',
    'pricing.additional.rushDelivery72': 'التسليم السريع (72 ساعة)',
    'pricing.additional.powerpoint': 'عرض تقديمي PowerPoint',
    'pricing.additional.excel': 'تحليل Excel/إحصائي',
    'pricing.additional.proofreading': 'المراجعة والتحرير',
    'pricing.additional.plagiarism': 'إزالة الانتحال',
    'pricing.additional.aiRemoval': 'إزالة المحتوى المُولد بالذكاء الاصطناعي',
    'pricing.additional.price.rush24': '+50% من السعر الأساسي',
    'pricing.additional.price.rush48': '+30% من السعر الأساسي',
    'pricing.additional.price.rush72': '+20% من السعر الأساسي',
    'pricing.additional.price.powerpoint': '200 لكل شريحة',
    'pricing.additional.price.excel': '375 في الساعة',
    'pricing.additional.price.proofreading': '125 لكل ورقة',
    'pricing.additional.price.plagiarism': '200 لكل ورقة',
    'pricing.additional.price.aiRemoval': '200 لكل ورقة',
    'pricing.payment.title': 'طرق الدفع',
    'pricing.payment.subtitle': 'نقبل طرق دفع متعددة لراحتك',
    'pricing.payment.info': 'خيارات الدفع المتاحة',
    'pricing.payment.description': 'اتصل بنا للحصول على تفاصيل الدفع المحددة لطريقتك المفضلة. سنقدم لك تعليمات دفع آمنة بمجرد أن تصبح مستعداً للمتابعة.',
    'pricing.faq.title': 'الأسئلة الشائعة حول الأسعار',
    'pricing.faq.subtitle': 'أسئلة شائعة حول أسعارنا وشروط الدفع',
    'pricing.cta.title': 'مستعد للبدء؟',
    'pricing.cta.subtitle': 'اتصل بنا اليوم للحصول على عرض سعر مخصص بناءً على متطلباتك المحددة',
    'pricing.cta.getQuote': 'احصل على عرض سعر',
    'pricing.cta.viewServices': 'عرض الخدمات',
    
    // Offers
    'offers.title': 'عروض حصرية',
    'offers.subtitle': 'استفد من عروضنا الخاصة ووفر على خدمات أكاديمية متميزة. دعم التعليم الجيد لا يجب أن يكون مكلفاً!',
    'offers.claim': 'اطلب عروضك',
    'offers.badge': 'وقت محدود',
    'offers.amazing.title': 'صفقات ومزايا مذهلة',
    'offers.amazing.subtitle': 'نحن نؤمن بتقديم قيمة استثنائية لعملائنا من خلال هذه العروض الحصرية',
    'offers.terms.title': 'الشروط والأحكام',
    'offers.terms.subtitle': 'يرجى قراءة شروط عروضنا بعناية لفهم كيفية المطالبة بهذه المزايا',
    'offers.termsImportant': 'مهم',
    'offers.cta.title': 'لا تفوت هذه العروض المذهلة!',
    'offers.cta.subtitle': 'اتصل بنا اليوم للمطالبة بمزاياك والبدء بخدمات أكاديمية متميزة',
    'offers.cta.getStarted': 'ابدأ الآن',
    'offers.cta.viewServices': 'عرض الخدمات',
    'offers.ctaLimited': 'عرض لوقت محدود',
    
    // Chatbot
    'chatbot.title': 'مساعد أكاديمي ذكي',
    'chatbot.welcome': '👋 مرحبًا! أنا مساعدك الأكاديمي الذكي. يمكنني مساعدتك في معلومات عن خدماتنا والأسعار وإجراء الطلبات وإرشادك خلال عملية الدعم الأكاديمي. ما اسمك؟',
    'chatbot.thinking': 'يفكر...',
    'chatbot.poweredBy': 'مساعد ذكي',
    'chatbot.clearChat': 'مسح المحادثة',
    'chatbot.translating': 'جاري الترجمة...',
    'chatbot.quickStart': 'بداية سريعة:',
    'chatbot.error': 'أعتذر، أواجه صعوبات تقنية. يرجى التواصل معنا مباشرة عبر واتساب على +447482576463 أو من خلال نموذج الاتصال للحصول على مساعدة فورية لاحتياجاتك الأكاديمية.',
    'chatbot.connectionError': 'أواجه مشكلة في الاتصال الآن. يرجى التواصل معنا على واتساب +447482576463 للحصول على مساعدة فورية!',
    'chatbot.whatsappMessage.withName': 'مرحبًا! أنا ${userName}. كنت أتحدث مع مساعدكم الذكي وأرغب في مناقشة متطلباتي الأكاديمية.',
    'chatbot.whatsappMessage.default': 'مرحبًا! كنت أتحدث مع مساعدكم الذكي وأرغب في مناقشة متطلباتي الأكاديمية.',
    'chatbot.quickReply.services': 'ما الخدمات التي تقدمونها؟',
    'chatbot.quickReply.pricing': 'كم التكلفة؟',
    'chatbot.quickReply.freeServices': 'أخبرني عن الخدمات المجانية',
    'chatbot.quickReply.order': 'كيف أضع طلب؟',
    'chatbot.quickReply.discounts': 'ما هي الخصومات الحالية؟',
    'chatbot.placeholder': 'اكتب رسالتك...',
    'chatbot.greeting': 'مرحبًا! ما اسمك حتى أتمكن من مساعدتك بشكل أفضل؟',
    'chatbot.welcomeWithName': 'سعدت بلقائك، {name}! كيف يمكنني مساعدتك اليوم؟',
    'chatbot.services': 'نحن نقدم خدمات أكاديمية شاملة:\n\n• المهام الأكاديمية\n• كتابة الرسائل\n• أوراق البحث\n• مساعدة الأطروحة\n• كتابة المقالات\n• نشر البحوث\n• التدريس الإلكتروني\n• إزالة السرقة الأدبية والذكاء الاصطناعي\n\nما الخدمة التي تهمك أكثر؟',
    'chatbot.pricing': 'تختلف أسعارنا بناءً على:\n• المستوى الأكاديمي (المدرسة الثانوية، الكلية، الدراسات العليا)\n• تعقيد الموضوع\n• إلحاح الموعد النهائي\n• عدد الصفحات\n\nنحن نقدم أيضًا:\n• خصم 30% على الطلبات الأولى\n• خصم 30% على الطلبات التي تزيد عن 1000 دولار\n• تقارير مجانية للسرقة الأدبية والذكاء الاصطناعي\n\nما نوع المهمة التي تحتاج مساعدة فيها؟',
    'chatbot.order': 'لإجراء طلب:\n1. أخبرني بمتطلباتك\n2. احصل على عرض سعر مخصص\n3. أكد وادفع\n4. استلم عملك المكتمل\n\nفي أي موضوع هو واجبك؟',
    'chatbot.free': 'تشمل خدماتنا المجانية:\n• تقارير كشف السرقة الأدبية والذكاء الاصطناعي\n• استشارة إرشادية للواجبات\n• اقتراح بحث (حتى صفحة واحدة)\n• مراجعات غير محدودة على الأعمال المدفوعة\n\nهذه الخدمات مشمولة دائمًا دون أي تكلفة إضافية! هل ترغب في معرفة المزيد عن أي خدمة معينة؟',
    'chatbot.discounts': 'العروض الحالية:\n• خصم 30% على الطلب الأول للعملاء الجدد\n• خصم 30% على الطلبات التي تزيد عن 1000 دولار\n• تقارير مجانية للسرقة الأدبية والذكاء الاصطناعي\n• اقتراحات بحث مجانية\n• مراجعات مجانية غير محدودة\n\nهل أنت مستعد للبدء في طلبك الأول؟',
    'chatbot.serviceSelected': 'اختيار رائع! {service} هي واحدة من خدماتنا الأكثر شعبية. لإعطائك عرض سعر دقيق، أحتاج إلى بعض التفاصيل:\n\n• كم عدد الصفحات التي تحتاجها؟\n• ما هو موعد التسليم؟\n• ما هو المستوى الأكاديمي؟\n\nأم تود أن أوصلك بفريقنا لاستشارة مفصلة؟',
    'chatbot.connect': 'رائع! لقد أخطرت فريقنا المحترف بشأن استفسارك{name}. سيتواصلون معك قريبًا لمساعدتك بشكل مخصص.\n\nلخدمة أسرع، يرجى زيارة صفحة الاتصال الخاصة بنا وتقديم تفاصيلك. هل هناك أي شيء آخر يمكنني مساعدتك به؟',
    'chatbot.levels': 'نحن ندعم جميع المستويات الأكاديمية:\n\n• المدرسة الثانوية - 300 لكل ورقة\n• البكالوريوس - 450 لكل ورقة\n• الماجستير - 625 لكل ورقة\n• الدكتوراه - 875 لكل ورقة\n\nقد تختلف الأسعار بناءً على تعقيد الموضوع وموعد التسليم. ما المستوى الذي تحتاج مساعدة فيه؟',
    'chatbot.deadlines': 'نحن نتعامل مع مواعيد نهائية متنوعة:\n\n• 24 ساعة (+50% رسوم عاجلة)\n• 48 ساعة (+30% رسوم عاجلة)\n• 3-7 أيام (أسعار معيارية)\n• 1+ أسابيع (أفضل الأسعار)\n\nما هو موعد التسليم الخاص بك؟',
    'chatbot.default': 'سأكون سعيدًا بمساعدتك{name}! يمكنني تقديم معلومات حول خدماتنا، التسعير، الخصومات، ومساعدتك في تقديم طلب. ماذا تريد أن تعرف المزيد عنه؟',
    
    // Offers Items Arabic
    'offers.freePlagiarism.title': 'تقارير مجانية للسرقة الأدبية والذكاء الاصطناعي',
    'offers.freePlagiarism.desc': 'احصل على تقارير شاملة لكشف السرقة الأدبية والذكاء الاصطناعي مع كل طلب بدون تكلفة إضافية.',
    'offers.freePlagiarism.highlight': 'مجاني دائماً',
    'offers.freePlagiarism.feature1': 'تقرير مفصل للسرقة الأدبية',
    'offers.freePlagiarism.feature2': 'كشف محتوى الذكاء الاصطناعي',
    'offers.freePlagiarism.feature3': 'التحقق من الأصالة',
    'offers.freePlagiarism.feature4': 'ضمان الجودة',
    
    'offers.freeGuidance.title': 'إرشاد مجاني للمهام',
    'offers.freeGuidance.desc': 'احصل على إرشاد وخبرة من الخبراء لمهامك قبل تقديم الطلب.',
    'offers.freeGuidance.highlight': 'مجاني',
    'offers.freeGuidance.feature1': 'استشارة الموضوع',
    'offers.freeGuidance.feature2': 'إرشاد الهيكل',
    'offers.freeGuidance.feature3': 'توصيات المصادر',
    'offers.freeGuidance.feature4': 'اقتراحات النهج',
    
    'offers.freeResearch.title': 'اقتراح بحث مجاني',
    'offers.freeResearch.desc': 'احصل على اقتراح بحث كامل حتى صفحة واحدة مجاناً تماماً لبدء بحثك.',
    'offers.freeResearch.highlight': 'حتى صفحة واحدة مجاناً',
    'offers.freeResearch.feature1': 'بيان المشكلة',
    'offers.freeResearch.feature2': 'أهداف البحث',
    'offers.freeResearch.feature3': 'مخطط المنهجية',
    'offers.freeResearch.feature4': 'نظرة عامة على الأدبيات',
    
    'offers.firstOrder.title': 'خصم 25% على الطلب الأول',
    'offers.firstOrder.desc': 'العملاء الجدد يحصلون على خصم حصري 25% على طلبهم الأول معنا.',
    'offers.firstOrder.highlight': 'خصم 25%',
    'offers.firstOrder.feature1': 'صالح للعملاء الجدد',
    'offers.firstOrder.feature2': 'جميع الخدمات مشمولة',
    'offers.firstOrder.feature3': 'لا يوجد حد أدنى للطلب',
    'offers.firstOrder.feature4': 'عرض لمرة واحدة',
    
    'offers.bulkOrder.title': 'خصم 20% على الطلبات فوق 650',
    'offers.bulkOrder.desc': 'وفر بشكل كبير على الطلبات الكبيرة مع خصمنا للطلبات التي تتجاوز 650.',
    'offers.bulkOrder.highlight': 'توفير بالجملة',
    'offers.bulkOrder.feature1': 'خصم تلقائي',
    'offers.bulkOrder.feature2': 'جميع الخدمات مؤهلة',
    'offers.bulkOrder.feature3': 'قابل للدمج مع عروض أخرى',
    'offers.bulkOrder.feature4': 'لا يوجد تاريخ انتهاء',
    
    'offers.revisions.title': 'مراجعات غير محدودة',
    'offers.revisions.desc': 'احصل على مراجعات مجانية غير محدودة على جميع المهام المدفوعة حتى تكون راضياً تماماً.',
    'offers.revisions.highlight': 'مضمن دائماً',
    'offers.revisions.feature1': 'لا توجد حدود للمراجعات',
    'offers.revisions.feature2': 'مجاني',
    'offers.revisions.feature3': 'ضمان 30 يوماً',
    'offers.revisions.feature4': 'ضمان الجودة',
    
    'offers.claimNow': 'اطلب الآن',
    'offers.termsGeneral': 'شروط عامة',
    'offers.termsGeneral.term1': 'جميع العروض تخضع للتوفر وقد يتم تعديلها أو إيقافها في أي وقت',
    'offers.termsGeneral.term2': 'لا يمكن دمج العروض إلا إذا تم النص عليه صراحة',
    'offers.termsGeneral.term3': 'الخدمات المجانية تُقدم كما هي وتخضع لإرشادات الجودة المعتادة لدينا',
    'offers.termsDiscount': 'شروط الخصم',
    'offers.termsDiscount.term1': 'خصم العميل لأول مرة ينطبق فقط على العملاء الجدد الذين لم يستخدموا خدماتنا من قبل',
    'offers.termsDiscount.term2': 'خصم الجملة للطلبات فوق 650 يُطبق تلقائياً عند الدفع',
    'offers.termsDiscount.term3': 'الخصومات تُحسب قبل الضرائب والرسوم الإضافية',
    'offers.termsRevision': 'سياسة المراجعة',
    'offers.termsRevision.term1': 'المراجعات غير المحدودة متاحة لمدة 30 يوماً بعد التسليم',
    'offers.termsRevision.term2': 'المراجعات يجب أن تكون ضمن نطاق العمل الأصلي',
    'offers.termsRevision.term3': 'التغييرات الكبيرة في المتطلبات قد تتطلب رسوماً إضافية',
    
    // Subject Names Arabic
    'subject.business': 'الأعمال والإدارة',
    'subject.computerScience': 'علوم الحاسوب',
    'subject.engineering': 'الهندسة',
    'subject.literature': 'الأدب واللغة الإنجليزية',
    'subject.psychology': 'علم النفس',
    'subject.sociology': 'علم الاجتماع',
    'subject.history': 'التاريخ',
    'subject.mathematics': 'الرياضيات',
    'subject.science': 'العلوم',
    'subject.law': 'القانون',
    'subject.medicine': 'الطب',
    'subject.technology': 'التكنولوجيا',
    'subject.finance': 'المالية',
    'subject.education': 'التعليم',
    'subject.healthcare': 'الرعاية الصحية',
    'subject.management': 'الإدارة',
    'subject.socialSciences': 'العلوم الاجتماعية',
    'subject.philosophy': 'الفلسفة',
    'subject.other': 'أخرى',
    
    // Team Roles Arabic
    'team.academicDirector': 'المدير الأكاديمي',
    'team.researchSpecialist': 'أخصائي البحوث',
    'team.writingCoordinator': 'منسق الكتابة',
    'team.director': 'المدير العام',
    'team.itManager': 'مدير تقنية المعلومات',
    'team.marketingSalesManager': 'مدير التسويق والمبيعات',
    'team.experience.sarah': '12+ سنة',
    'team.experience.james': '15+ سنة',
    'team.experience.maria': '10+ سنة',
    'team.experience.director': '15+ سنة',
    'team.experience.itManager': '8+ سنة',
    'team.experience.raja': '7+ سنة',
    'team.literatureHumanities': 'الأدب والعلوم الإنسانية',
    'team.sciencesTechnology': 'العلوم والتكنولوجيا',
    'team.businessStrategy': 'استراتيجية الأعمال والقيادة',
    'team.technologyManagement': 'إدارة التكنولوجيا والبنية التحتية',
    'team.marketingAndSales': 'التسويق والمبيعات وعلاقات العملاء',
    
    // Samples
    'samples.title': 'أعمال نموذجية',
    'samples.subtitle': 'استكشف مجموعتنا من النماذج الأكاديمية عالية الجودة عبر مختلف المواضيع والتنسيقات',
    'samples.viewSamples': 'عرض فئات النماذج',
    'samples.categories.title': 'فئات النماذج',
    'samples.categories.subtitle': 'تصفح مجموعتنا المتنوعة من النماذج الأكاديمية المنظمة حسب النوع والموضوع',
    'samples.benefits.title': 'لماذا تعرض نماذجنا؟',
    'samples.benefits.subtitle': 'فهم الجودة من خلال الأمثلة يساعدك على اتخاذ قرارات مدروسة',
    'samples.explore.title': 'مستعد لاستكشاف؟',
    'samples.explore.subtitle': 'تصفح نماذجنا لفهم جودة وأسلوب عملنا الأكاديمي',
    'samples.explore.browse': 'تصفح جميع النماذج',
    'samples.explore.getStarted': 'ابدأ بطلبك',
    
    // Sample Categories Arabic
    'samples.category.essays': 'المقالات',
    'samples.category.researchPapers': 'أوراق البحث',
    'samples.category.thesis': 'نماذج الرسائل',
    'samples.category.caseStudies': 'دراسات الحالة',
    'samples.category.dissertations': 'الأطروحات',
    'samples.category.reports': 'التقارير',
    'samples.category.essays.desc': 'مقالات حجاجية وسردية ووصفية وتحليلية عبر مختلف المواضيع.',
    'samples.category.researchPapers.desc': 'أوراق بحثية شاملة مع منهجية وتوثيق مناسب.',
    'samples.category.thesis.desc': 'أمثلة رسائل كاملة من مختلف المستويات الأكاديمية والتخصصات.',
    'samples.category.caseStudies.desc': 'تحليلات مفصلة لدراسات الحالة عبر مختلف الصناعات والمواضيع.',
    'samples.category.dissertations.desc': 'نماذج أطروحات شاملة مع فصول كاملة وتحليل.',
    'samples.category.reports.desc': 'تقارير مهنية تشمل تقارير المختبر وتقارير الأعمال وتقارير المشاريع.',
    'samples.category.count': 'نماذج',
    
    // Featured Samples Arabic
    'samples.featured.socialMedia.title': 'تأثير وسائل التواصل الاجتماعي على التواصل الحديث',
    'samples.featured.socialMedia.type': 'ورقة بحثية',
    'samples.featured.socialMedia.subject': 'دراسات التواصل',
    'samples.featured.socialMedia.desc': 'تحليل شامل لكيفية تغيير منصات وسائل التواصل الاجتماعي لأنماط التواصل الشخصي في العصر الرقمي.',
    'samples.featured.business.title': 'الممارسات التجارية المستدامة في القرن الحادي والعشرين',
    'samples.featured.business.type': 'دراسة حالة',
    'samples.featured.business.subject': 'إدارة الأعمال',
    'samples.featured.business.desc': 'دراسة حالة متعمقة تبحث كيف تدمج الشركات الحديثة الاستدامة في نماذج أعمالها.',
    'samples.featured.climate.title': 'تغير المناخ وآثاره الاقتصادية',
    'samples.featured.climate.type': 'رسالة',
    'samples.featured.climate.subject': 'الاقتصاد البيئي',
    'samples.featured.climate.desc': 'رسالة مفصلة تستكشف التكاليف والفوائد الاقتصادية لاستراتيجيات تخفيف تغير المناخ.',
    'samples.featured.aiHealthcare.title': 'الذكاء الاصطناعي في التحليلات التنبؤية للرعاية الصحية لأمراض القلب',
    'samples.featured.aiHealthcare.type': 'مقترح بحثي',
    'samples.featured.aiHealthcare.subject': 'تكنولوجيا الرعاية الصحية',
    'samples.featured.aiHealthcare.desc': 'مقترح بحثي شامل يستكشف تطبيقات الذكاء الاصطناعي في التحليلات التنبؤية لاكتشاف ومنع أمراض القلب.',
    'samples.featured.aiWeather.title': 'الذكاء الاصطناعي في التنبؤ بالطقس باستخدام الصور الساتلية',
    'samples.featured.aiWeather.type': 'ورقة بحثية',
    'samples.featured.aiWeather.subject': 'علوم الحاسوب',
    'samples.featured.aiWeather.desc': 'بحث متقدم حول استخدام الذكاء الاصطناعي والصور الساتلية للتنبؤ الدقيق بالطقس ونمذجة المناخ.',
    'samples.featured.pythonProblem.title': 'Python لحل المشاكل في العالم الحقيقي',
    'samples.featured.pythonProblem.type': 'واجب',
    'samples.featured.pythonProblem.subject': 'برمجة الحاسوب',
    'samples.featured.pythonProblem.desc': 'واجب عملي يظهر مهارات برمجة Python من خلال تطبيقات وتنفيذ حلول للمشاكل الواقعية.',
    'samples.level.graduate': 'خريج',
    'samples.level.mba': 'ماجستير إدارة أعمال',
    'samples.level.masters': 'ماجستير',
    'samples.level.phd': 'دكتوراه',
    'samples.level.undergraduate': 'بكالوريوس',
    'samples.pages': 'صفحات',
    'samples.viewSample': 'عرض النموذج',
    'samples.request': 'طلب',
    'samples.requestSamples': 'طلب نماذج',
    'samples.requestSampleAccess': 'طلب الوصول للنماذج',
    'samples.availableSubjects': 'المواضيع المتاحة',
    'samples.subject': 'الموضوع',
    'samples.featuredTitle': 'أعمال نموذجية مميزة',
    'samples.featuredSubtitle': 'معاينة بعض أعمالنا الأكاديمية عالية الجودة عبر مختلف التخصصات',
    'samples.howToAccess.title': 'كيفية الوصول للأعمال النموذجية',
    'samples.howToAccess.subtitle': 'اتبع هذه الخطوات البسيطة للحصول على الوصول لمكتبة النماذج الشاملة لدينا',
    'samples.step.contact.title': 'اتصل بنا',
    'samples.step.contact.desc': 'تواصل معنا من خلال نموذج الاتصال أو قنوات التواصل المباشرة.',
    'samples.step.specify.title': 'حدد المتطلبات',
    'samples.step.specify.desc': 'أخبرنا نوع النماذج التي تحتاجها - الموضوع والمستوى الأكاديمي والتنسيق.',
    'samples.step.receive.title': 'استلم النماذج',
    'samples.step.receive.desc': 'احصل على الوصول للأعمال النموذجية ذات الصلة منظمة في مجلدات سهلة التنقل.',
    'samples.quality.title': 'لماذا تتميز نماذجنا',
    'samples.quality.subtitle': 'أعمالنا النموذجية تمثل نفس المعايير العالية والجودة التي نقدمها لجميع عملائنا.',
    'samples.quality.benefit1': 'مكتوبة من قبل خبراء حاصلين على درجة الدكتوراه',
    'samples.quality.benefit2': 'منسقة ومستشهدة بشكل صحيح',
    'samples.quality.benefit3': 'أصلية وخالية من السرقة الأدبية',
    'samples.quality.benefit4': 'بحث وتحليل شامل',
    'samples.quality.benefit5': 'مستويات أكاديمية متعددة مغطاة',
    'samples.quality.benefit6': 'مجالات موضوعية متنوعة مدرجة',
    'samples.note': 'سيتم توفير الأعمال النموذجية بتنسيق مجلد عند الطلب. اتصل بنا للوصول لمكتبة النماذج الكاملة لدينا.',
    'samples.demo': 'هذا نموذج تجريبي. اتصل بنا للحصول على الوصول الكامل لمكتبة النماذج لدينا.',
    'samples.readOnly': 'مستند نموذجي - للقراءة فقط',
    
    // Footer
    'footer.description': 'تقديم خدمات كتابة أكاديمية استثنائية لمساعدة الطلاب على التفوق في رحلتهم التعليمية. الجودة والموثوقية والتميز الأكاديمي هي أولوياتنا الرئيسية.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.copyright': '© 2024 Thesis Assignment Hub. جميع الحقوق محفوظة.',
    
    // Common
    'common.free': 'مجاني',
    'common.getQuote': 'احصل على عرض سعر',
    'common.learnMore': 'اعرف المزيد',
    'common.contactUs': 'اتصل بنا',
    'common.viewAll': 'عرض الكل',
    'common.readMore': 'اقرأ المزيد',
    'common.loading': 'جاري التحميل...',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.close': 'إغلاق',
    'common.minimize': 'تصغير',
    'common.maximize': 'تكبير',
    'common.viewPricing': 'عرض الأسعار',
    'common.support': 'الدعم',
    'common.original': 'أصلي',
    'common.satisfaction': 'الرضا',
    'common.rating': 'التقييم',
    
    // WhatsApp Widget
    'whatsapp.contactButton': 'اتصل بنا عبر الواتساب',
    'whatsapp.modalTitle': 'رسالة واتساب',
    'whatsapp.modalSubtitle': 'أرسل لنا رسالة',
    'whatsapp.messageLabel': 'رسالتك',
    'whatsapp.messagePlaceholder': 'اكتب رسالتك هنا...',
    'whatsapp.description': 'سنتلقى رسالتك على الواتساب وسنعود إليك في أقرب وقت ممكن.',
    'whatsapp.cancel': 'إلغاء',
    'whatsapp.send': 'إرسال',
    
    // Service Features
    'feature.academicAssignments': 'المهام الأكاديمية',
    'feature.thesisWriting': 'كتابة الرسائل',
    'feature.researchPapers': 'أوراق البحث',
    'feature.dissertationHelp': 'مساعدة الأطروحة',
    'feature.essayWriting': 'كتابة المقالات',
    'feature.researchPublication': 'نشر البحوث في المجلات',
    'feature.onlineTeaching': 'التدريس الإلكتروني',
    'feature.plagiarismRemoval': 'إزالة السرقة الأدبية والذكاء الاصطناعي',
    'feature.paperPreparation': 'إعداد الأوراق',
    'feature.researchProposal': 'اقتراح البحث',
          'feature.other': 'أخرى',
    
    // Service Descriptions
    'service.academicAssignments.desc': 'مساعدة شاملة في المقالات والتقارير ودراسات الحالة وجميع أنواع المهام الأكاديمية.',
    'service.thesisWriting.desc': 'مساعدة خبراء في كتابة الرسائل من تطوير الاقتراح إلى التقديم النهائي.',
    'service.researchPapers.desc': 'أوراق بحثية متعمقة مع تحليل شامل ودقة أكاديمية.',
    'service.dissertationHelp.desc': 'دعم كامل للأطروحة من اختيار الموضوع إلى التحضير للدفاع النهائي.',
    'service.essayWriting.desc': 'خدمات كتابة المقالات المهنية لجميع المستويات الأكاديمية والمواضيع.',
    'service.researchProposal.desc': 'اقتراحات بحثية منظمة تحصل على موافقة اللجان الأكاديمية.',
    'service.researchPublication.desc': 'دعم مهني لنشر بحثك في المجلات الأكاديمية المرموقة.',
    'service.onlineTeaching.desc': 'جلسات تعليم إلكترونية شخصية وإرشاد للمهام.',
    'service.plagiarismRemoval.desc': 'خدمة مهنية لإزالة السرقة الأدبية والمحتوى المولد بالذكاء الاصطناعي من عملك.',
    'service.paperPreparation.desc': 'خدمة إعداد الأوراق الكاملة بما في ذلك التنسيق والمراجع والمراجعة النهائية.',
    'service.freePlagiarism.title': 'تقارير مجانية للسرقة الأدبية والذكاء الاصطناعي',
    'service.freePlagiarism.desc': 'احصل على تقارير شاملة لكشف السرقة الأدبية والذكاء الاصطناعي مع كل طلب بدون تكلفة إضافية.',
    'service.freeGuidance.title': 'إرشاد مجاني للمهام',
    'service.freeGuidance.desc': 'احصل على إرشاد وخبرة من الخبراء لمهامك قبل تقديم الطلب.',
    
    // Service Pricing
    'service.pricing.custom': 'تسعير مخصص حسب المتطلبات',
    'service.pricing.tailored': 'تسعير مخصص لدعم الرسائل الشامل',
    'service.pricing.competitive': 'أسعار تنافسية حسب التعقيد والطول',
    'service.pricing.comprehensive': 'حزم شاملة متاحة',
    'service.pricing.affordable': 'أسعار معقولة تبدأ من المستوى الأساسي',
    'service.pricing.premium': 'خدمة متميزة مع ضمان النشر',
    'service.pricing.hourly': 'أسعار ساعية مع جدولة مرنة',
    'service.pricing.perPage': 'تسعير تنافسي لكل صفحة',
    'service.pricing.formatting': 'أسعار معقولة للتنسيق والإعداد',
    
    // Service Features
    'service.feature.allLevels': 'جميع المستويات الأكاديمية',
    'service.feature.variousSubjects': 'مواضيع متنوعة',
    'service.feature.originalContent': 'محتوى أصلي',
    'service.feature.properFormatting': 'تنسيق صحيح',
    'service.feature.researchProposal': 'اقتراح البحث',
    'service.feature.literatureReview': 'مراجعة الأدبيات',
    'service.feature.methodologyDesign': 'تصميم المنهجية',
    'service.feature.dataAnalysis': 'تحليل البيانات',
    'service.feature.originalResearch': 'بحث أصلي',
    'service.feature.peerReviewReady': 'جاهز لمراجعة الأقران',
    'service.feature.citationIncluded': 'المراجع مضمنة',
    'service.feature.qualitySources': 'مصادر عالية الجودة',
    'service.feature.topicSelection': 'اختيار الموضوع',
    'service.feature.chapterWiseWriting': 'كتابة حسب الفصول',
    'service.feature.defensePreparation': 'إعداد الدفاع',
    'service.feature.revisionSupport': 'دعم المراجعة',
    'service.feature.argumentativeEssays': 'مقالات جدلية',
    'service.feature.narrativeEssays': 'مقالات سردية',
    'service.feature.descriptiveEssays': 'مقالات وصفية',
    'service.feature.compareContrast': 'مقارنة وتباين',
    'service.feature.problemStatement': 'بيان المشكلة',
    'service.feature.literatureGap': 'فجوة الأدبيات',
    'service.feature.methodology': 'المنهجية',
    'service.feature.timeline': 'الجدول الزمني',
    'service.feature.journalSelection': 'اختيار المجلة',
    'service.feature.manuscriptPreparation': 'إعداد المخطوطة',
    'service.feature.peerReviewSupport': 'دعم مراجعة الأقران',
    'service.feature.publicationGuidance': 'إرشاد النشر',
    'service.feature.oneOnOneSessions': 'جلسات فردية',
    'service.feature.assignmentWalkthrough': 'شرح المهام',
    'service.feature.conceptClarification': 'توضيح المفاهيم',
    'service.feature.studyGuidance': 'إرشاد الدراسة',
    'service.feature.contentRewriting': 'إعادة كتابة المحتوى',
    'service.feature.originalityEnhancement': 'تعزيز الأصالة',
    'service.feature.qualityImprovement': 'تحسين الجودة',
    'service.feature.reportIncluded': 'التقرير مضمن',
    'service.feature.academicFormatting': 'التنسيق الأكاديمي',
    'service.feature.citationStyles': 'أنماط الاستشهاد',
    'service.feature.proofreading': 'التدقيق اللغوي',
    'service.feature.finalReview': 'المراجعة النهائية',
    'service.feature.detailedReport': 'تقرير مفصل للسرقة الأدبية',
    'service.feature.aiDetection': 'كشف محتوى الذكاء الاصطناعي',
    'service.feature.originalityVerification': 'التحقق من الأصالة',
    'service.feature.qualityAssurance': 'ضمان الجودة',
    'service.feature.topicConsultation': 'استشارة الموضوع',
    'service.feature.structureGuidance': 'إرشاد الهيكل',
    'service.feature.resourceRecommendations': 'توصيات المصادر',
    'service.feature.approachSuggestions': 'اقتراحات النهج',
    
    'service.freeService': 'خدمة مجانية',
    'service.getFreeService': 'احصل على الخدمة المجانية',
    
    // Stats
    'stats.projectsCompleted': 'مشروع مكتمل',
    'stats.clientSatisfaction': 'رضا العملاء',
    'stats.supportAvailable': 'دعم متاح',
    'stats.yearsExperience': 'سنوات خبرة',
    'stats.expertWriters': 'كاتب خبير',
    
    // Home Page Service Descriptions
    'home.service.academicAssignments.desc': 'مساعدة شاملة في جميع أنواع المهام الأكاديمية عبر مختلف المواضيع.',
    'home.service.thesisWriting.desc': 'مساعدة خبراء في كتابة الرسائل، من الاقتراح إلى التقديم النهائي.',
    'home.service.researchPublication.desc': 'دعم مهني لنشر بحثك في المجلات الأكاديمية المرموقة.',
    
    // Home Page Testimonials
    'home.testimonial.sarah.name': 'سارة جونسون',
    'home.testimonial.sarah.role': 'طالبة دراسات عليا',
    'home.testimonial.sarah.content': 'جودة العمل فاقت توقعاتي. تم إكمال رسالتي في الوقت المحدد وبعمق بحثي استثنائي.',
    'home.testimonial.michael.name': 'مايكل تشين',
    'home.testimonial.michael.role': 'مرشح دكتوراه',
    'home.testimonial.michael.content': 'خدمة مهنية مع تواصل ممتاز طوال العملية. أوصي بشدة للعمل البحثي.',
    'home.testimonial.emma.name': 'إيما ديفيس',
    'home.testimonial.emma.role': 'طالبة جامعية',
    'home.testimonial.emma.content': 'ساعدني على فهم المفاهيم المعقدة بينما قدم مهام عالية الجودة. تجربة تعلم رائعة.',
    
    // Services Page Process Steps
    'services.process.step1.title': 'تقديم المتطلبات',
    'services.process.step1.desc': 'شارك تفاصيل مهمتك والإرشادات والموعد النهائي معنا.',
    'services.process.step2.title': 'احصل على عرض سعر',
    'services.process.step2.desc': 'احصل على عرض سعر تنافسي بناءً على متطلباتك المحددة.',
    'services.process.step3.title': 'تعيين خبير',
    'services.process.step3.desc': 'يتم تكليف عملك لخبير مؤهل في مجال موضوعك.',
    'services.process.step4.title': 'تسليم جودة',
    'services.process.step4.desc': 'احصل على عملك المكتمل في الوقت المحدد مع مراجعات غير محدودة.',
    
    // Pricing FAQ
    'pricing.faq.q1': 'كيف يتم حساب السعر النهائي؟',
    'pricing.faq.a1': 'يعتمد السعر النهائي على المستوى الأكاديمي وعدد الصفحات والموعد النهائي وأي خدمات إضافية. نحن نقدم عرض سعر مفصل قبل تأكيد طلبك.',
    'pricing.faq.q2': 'هل توجد رسوم مخفية؟',
    'pricing.faq.a2': 'لا، نحن نؤمن بالتسعير الشفاف. عرض السعر الذي تتلقاه يشمل جميع التكاليف باستثناء الخدمات الإضافية الاختيارية التي تطلبها تحديداً.',
    'pricing.faq.q3': 'هل تقدمون خصومات للطلبات الكبيرة؟',
    'pricing.faq.a3': 'نعم! الطلبات التي تزيد عن 25,000 تحصل تلقائياً على خصم 30%. نقدم أيضاً أسعار خاصة للعملاء طويلي المدى والعملاء المتكررين.',
    'pricing.faq.q4': 'ما طرق الدفع التي تقبلونها؟',
    'pricing.faq.a4': 'نقبل طرق دفع متنوعة تشمل بطاقات الائتمان الرئيسية والمحافظ الرقمية وخدمات التحويل الدولي. اتصل بنا للحصول على تفاصيل الدفع المحددة.',
    'pricing.faq.q5': 'هل توجد سياسة استرداد؟',
    'pricing.faq.a5': 'نعم، نقدم سياسة استرداد شاملة. إذا لم تكن راضياً عن العمل، نقدم مراجعات مجانية غير محدودة أو استرداد كامل في الحالات المؤهلة.',
    
    // Home Page Why Choose Us Benefits
    'home.benefit.expertWriters': 'كتّاب خبراء حاصلون على درجات متقدمة',
    'home.benefit.freePlagiarism': 'تقارير مجانية للسرقة الأدبية والذكاء الاصطناعي',
    'home.benefit.freeRevisions': 'مراجعات مجانية غير محدودة',
    'home.benefit.timelyDelivery': 'التسليم في الوقت المحدد مضمون',
    'home.benefit.support247': 'دعم العملاء متاح على مدار الساعة',
    'home.benefit.confidential': 'خدمة سرية وآمنة',
    
    // Home Page Rating Section
    'home.rating.title': 'تقييم 4.9/5',
    'home.rating.subtitle': 'من أكثر من 500 عميل راضٍ',
    'home.rating.expertTeam': 'فريق خبراء',
    'home.rating.qualityAssured': 'جودة مضمونة',
    
    // Services Page Features
    'services.feature.onTimeDelivery.title': 'التسليم في الوقت المحدد',
    'services.feature.onTimeDelivery.desc': 'لا تفوت موعداً نهائياً أبداً',
    'services.feature.qualityGuaranteed.title': 'الجودة مضمونة',
    'services.feature.qualityGuaranteed.desc': 'معايير أكاديمية عالية',
    'services.feature.originalWork.title': 'عمل أصلي',
    'services.feature.originalWork.desc': 'محتوى خالٍ من السرقة الأدبية',
    'services.feature.expertWriters.title': 'كتّاب خبراء',
    'services.feature.expertWriters.desc': 'محترفون مؤهلون بدرجة الدكتوراه',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'ar' : 'en';
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const isRTL = language === 'ar';

  const formatPrice = (price: string): string => {
    // Don't format percentage-based prices or prices that already contain currency symbols
    if (price.includes('%') || price.includes('من السعر الأساسي') || price.includes('of base price')) {
      return price;
    }
    
    const currency = translations[language]['currency.pkr'];
    
    // If Arabic language, convert PKR to SAR using formula: price/75
    if (language === 'ar') {
      const numericPrice = parseFloat(price);
      if (!isNaN(numericPrice)) {
        const convertedPrice = Math.ceil(numericPrice / 75);
        console.log('Original price:', numericPrice, 'Converted:', numericPrice / 75, 'Ceiling:', Math.ceil(numericPrice / 75));

        return `${currency} ${convertedPrice}`;
      }
    }
    
    return `${currency} ${price}`;
  };

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
